### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by cbbfcd** [cyco130/esbuild-plugin-polyfill-node#9]
hello, when i use this repo in our edge server platform, got an error:

Uncaught ReferenceError: navigator is not defined
  at node_modules/@jspm/core/nodelibs/browser/process.js (zone-2gh6amccdqq2_camp-edge-ssr.js:250:13)
  at __init (zone-2gh6amccdqq2_camp-edge-ssr.js:15:56)
  at node_modules/esbuild-plugin-polyfill-node/polyfills/process.js (zone-2gh6amccdqq2_camp-edge-ssr.js:431:5)
  at __init (zone-2gh6amccdqq2_camp-edge-ssr.js:15:56)
  at node_modules/@jspm/core/nodelibs/browser/buffer.js (zone-2gh6amccdqq2_camp-edge-ssr.js:2260:5)
  at __init (zone-2gh6amccdqq2_camp-edge-ssr.js:15:56)
  at node_modules/esbuild-plugin-polyfill-node/polyfills/buffer.js (zone-2gh6amccdqq2_camp-edge-ssr.js:2281:5)
  at __init (zone-2gh6amccdqq2_camp-edge-ssr.js:15:56)
  
  it's in `process`

**Comment by cyco130** [comment]
Can you give more details on your Edge platform? Maybe I can convince JSPM people to do an existence check on `navigator` first.

In the meantime, as a workaround, you can add `inject: ["/path/to/navigator.js"]` to your ESBuild config and create a `navigator.js` file in the suitable path wit contents similar to the following:

```javascript
export const navigator = {
  language: "en-US",
};
```

If JSPM people don't agree with this, we can add a similar polyfill ourselves.

**Comment by cyco130** [comment]
Just release 0.3.0 which brings `globals: { navigator: true }` to support the kind of environment you're using. I'm still interested in what environment it is, though.
